"""Added slave nodes table.

Revision ID: 659bfb078963
Revises: bbc7ff7dcfa9
Create Date: 2018-01-26 23:40:48.792837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659bfb078963'
down_revision = 'bbc7ff7dcfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masternode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nodename', sa.String(length=64), nullable=True),
    sa.Column('datafile', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('ipaddress', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masternode_datafile'), 'masternode', ['datafile'], unique=True)
    op.create_index(op.f('ix_masternode_nodename'), 'masternode', ['nodename'], unique=True)
    op.create_table('slavenode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nodename', sa.String(length=64), nullable=True),
    sa.Column('datafile', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('ipaddress', sa.String(length=64), nullable=True),
    sa.Column('masternode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['masternode_id'], ['masternode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slavenode_datafile'), 'slavenode', ['datafile'], unique=True)
    op.create_index(op.f('ix_slavenode_nodename'), 'slavenode', ['nodename'], unique=True)
    op.drop_table('master_node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_node',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nodename', sa.VARCHAR(length=64), nullable=True),
    sa.Column('datafile', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ipaddress', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_slavenode_nodename'), table_name='slavenode')
    op.drop_index(op.f('ix_slavenode_datafile'), table_name='slavenode')
    op.drop_table('slavenode')
    op.drop_index(op.f('ix_masternode_nodename'), table_name='masternode')
    op.drop_index(op.f('ix_masternode_datafile'), table_name='masternode')
    op.drop_table('masternode')
    # ### end Alembic commands ###
