"""created MasterNode table

Revision ID: bbc7ff7dcfa9
Revises: 
Create Date: 2018-01-26 23:06:23.829371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc7ff7dcfa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nodename', sa.String(length=64), nullable=True),
    sa.Column('datafile', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('ipaddress', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_node_datafile'), 'master_node', ['datafile'], unique=True)
    op.create_index(op.f('ix_master_node_nodename'), 'master_node', ['nodename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_node_nodename'), table_name='master_node')
    op.drop_index(op.f('ix_master_node_datafile'), table_name='master_node')
    op.drop_table('master_node')
    # ### end Alembic commands ###
